version: '3'

networks:
  vnfap-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: vnfap/vnfap-server:latest
    command: hbbs -r vnfap.example.com:21117
    volumes:
      - ./data:/root
    networks:
      - vnfap-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: vnfap/vnfap-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - vnfap-net
    restart: unless-stopped
