#!/bin/sh

# PROVIDE: vnfap_hbbr
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# vnfap_hbbr_enable (bool):            Set to NO by default.
#               Set it to YES to enable vnfap_hbbr.
# vnfap_hbbr_args (string):            Set extra arguments to pass to vnfap_hbbr
#               Default is "-k _".
# vnfap_hbbr_user (string):            Set user that vnfap_hbbr will run under
#               Default is "root".
# vnfap_hbbr_group (string):           Set group that vnfap_hbbr will run under
#               Default is "wheel".

. /etc/rc.subr

name=vnfap_hbbr
desc="VNFap Relay Server"
rcvar=vnfap_hbbr_enable

load_rc_config $name

: ${vnfap_hbbr_enable:=NO}
: ${vnfap_hbbr_args="-k _"}
: ${vnfap_hbbr_user:=vnfap}
: ${vnfap_hbbr_group:=vnfap}

pidfile=/var/run/vnfap_hbbr.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/hbbr
vnfap_hbbr_chdir=/var/db/vnfap-server
command_args="-p ${pidfile} -o /var/log/vnfap-hbbr.log ${procname} ${vnfap_hbbr_args}"
## If you want the daemon do its log over syslog comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${vnfap_hbbr_args}"

start_precmd=vnfap_hbbr_startprecmd

vnfap_hbbr_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${vnfap_hbbr_user}:${vnfap_hbbr_group} ${pidfile};
    else
        install -o ${vnfap_hbbr_user} -g ${vnfap_hbbr_group} /dev/null ${pidfile};
    fi
    if [ -e ${vnfap_hbbr_chdir} ]; then
        chown -R ${vnfap_hbbr_user}:${vnfap_hbbr_group} ${vnfap_hbbr_chdir};
        chmod -R 770 ${vnfap_hbbr_chdir};
    else
        mkdir -m 770 ${vnfap_hbbr_chdir};
        chown ${vnfap_hbbr_user}:${vnfap_hbbr_group} ${vnfap_hbbr_chdir};
    fi
    if [ -e /var/log/vnfap-hbbr.log ]; then
        chown -R ${vnfap_hbbr_user}:${vnfap_hbbr_group} /var/log/vnfap-hbbr.log;
        chmod 660 /var/log/vnfap-hbbr.log;
    else
        install -o ${vnfap_hbbr_user} -g ${vnfap_hbbr_group} /dev/null /var/log/vnfap-hbbr.log;
        chmod 660 /var/log/vnfap-hbbr.log;
    fi
}

run_rc_command "$1"
