#!/bin/sh

# PROVIDE: vnfap_hbbs
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# vnfap_hbbs_enable (bool):            Set to NO by default.
#               Set it to YES to enable vnfap_hbbs.
# vnfap_hbbs_ip (string):              Set IP address/hostname of relay server to use
#               Defaults to "127.0.0.1", please replace with your server hostname/IP.
# vnfap_hbbs_args (string):            Set extra arguments to pass to vnfap_hbbs
#               Default is "-r ${vnfap_hbbs_ip} -k _".
# vnfap_hbbs_user (string):            Set user that vnfap_hbbs will run under
#               Default is "root".
# vnfap_hbbs_group (string):           Set group that vnfap_hbbs will run under
#               Default is "wheel".

. /etc/rc.subr

name=vnfap_hbbs
desc="VNFap ID/Rendezvous Server"
rcvar=vnfap_hbbs_enable

load_rc_config $name

: ${vnfap_hbbs_enable:=NO}
: ${vnfap_hbbs_ip:=127.0.0.1}
: ${vnfap_hbbs_args="-r ${vnfap_hbbs_ip} -k _"}
: ${vnfap_hbbs_user:=vnfap}
: ${vnfap_hbbs_group:=vnfap}

pidfile=/var/run/vnfap_hbbs.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/hbbs
vnfap_hbbs_chdir=/var/db/vnfap-server
command_args="-p ${pidfile} -o /var/log/vnfap-hbbs.log ${procname} ${vnfap_hbbs_args}"
## If you want the daemon to do its log over syslog, comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${vnfap_hbbs_args}"

start_precmd=vnfap_hbbs_startprecmd

vnfap_hbbs_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${vnfap_hbbs_user}:${vnfap_hbbs_group} ${pidfile};
    else
        install -o ${vnfap_hbbs_user} -g ${vnfap_hbbs_group} /dev/null ${pidfile};
    fi
    if [ -e ${vnfap_hbbs_chdir} ]; then
        chown -R ${vnfap_hbbs_user}:${vnfap_hbbs_group} ${vnfap_hbbs_chdir};
        chmod -R 770 ${vnfap_hbbs_chdir};
    else
        mkdir -m 770 ${vnfap_hbbs_chdir};
        chown ${vnfap_hbbs_user}:${vnfap_hbbs_group} ${vnfap_hbbs_chdir};
    fi
    if [ -e /var/log/vnfap-hbbs.log ]; then
        chown -R ${vnfap_hbbs_user}:${vnfap_hbbs_group} /var/log/vnfap-hbbs.log;
        chmod 660 /var/log/vnfap-hbbs.log;
    else
        install -o ${vnfap_hbbs_user} -g ${vnfap_hbbs_group} /dev/null /var/log/vnfap-hbbs.log;
        chmod 660 /var/log/vnfap-hbbs.log;
    fi
}

run_rc_command "$1"
